export const PLATFORM_SETTING_DEFS = [
  // ── General ───────────────────────────────────────
  {
    key: "platform_name",
    value: "MP-MLA Platform",
    type: "text",
    group: "general",
    label: "Platform Name",
    description: "Platform operator name",
    order: 1,
  },
  {
    key: "support_email",
    value: "support@admin.mpmla.in",
    type: "text",
    group: "general",
    label: "Support Email",
    description: "Support email shown to tenants",
    order: 2,
  },
  {
    key: "allow_tenant_creation",
    value: "true",
    type: "boolean",
    group: "general",
    label: "Allow Tenant Creation",
    description: "Allow operators to create new tenants",
    order: 3,
  },

  // ── Billing ───────────────────────────────────────
  {
    key: "default_trial_days",
    value: "14",
    type: "number",
    group: "billing",
    label: "Default Trial Period (Days)",
    description: "Default trial period for new tenants",
    order: 1,
  },
  {
    key: "renewal_reminder_days",
    value: "7",
    type: "number",
    group: "billing",
    label: "Renewal Reminder (Days)",
    description: "Days before renewal to send reminder",
    order: 2,
  },

  // ── Branding ──────────────────────────────────────
  {
    key: "brand_primary_color",
    value: "#2563eb",
    type: "color",
    group: "branding",
    label: "Primary Color",
    description: "Main theme color",
    order: 1,
  },
  {
    key: "brand_secondary_color",
    value: "#7c3aed",
    type: "color",
    group: "branding",
    label: "Secondary Color",
    description: "Accent color",
    order: 2,
  },
  {
    key: "brand_success_color",
    value: "#16a34a",
    type: "color",
    group: "branding",
    label: "Success Color",
    description: "Success/positive",
    order: 3,
  },
  {
    key: "brand_warning_color",
    value: "#d97706",
    type: "color",
    group: "branding",
    label: "Warning Color",
    description: "Warning/caution",
    order: 4,
  },
  {
    key: "brand_danger_color",
    value: "#dc2626",
    type: "color",
    group: "branding",
    label: "Danger Color",
    description: "Error/destructive",
    order: 5,
  },
  {
    key: "brand_logo_url",
    value: "",
    type: "image",
    group: "branding",
    label: "Logo",
    description: "Organization logo image (PNG, JPG, SVG)",
    order: 6,
  },
  {
    key: "brand_favicon_url",
    value: "",
    type: "image",
    group: "branding",
    label: "Favicon",
    description: "Browser tab icon (PNG, ICO, SVG)",
    order: 7,
  },
  {
    key: "brand_sidebar_style",
    value: "default",
    type: "select",
    group: "branding",
    label: "Sidebar Style",
    description: "Navigation style",
    options: ["default", "compact", "minimal"],
    order: 8,
  },
  {
    key: "brand_login_bg",
    value: "gradient",
    type: "select",
    group: "branding",
    label: "Login Page Background",
    description: "Login screen style",
    options: ["gradient", "solid", "image"],
    order: 9,
  },
  {
    key: "brand_footer_text",
    value: "Powered by Vibrantick Infotech Solutions",
    type: "text",
    group: "branding",
    label: "Footer Text",
    description: "Shown at bottom of pages",
    order: 10,
  },

  // ── Security ──────────────────────────────────────
  {
    key: "session_timeout_minutes",
    value: "30",
    type: "number",
    group: "security",
    label: "Session Timeout (minutes)",
    description: "Auto-logout after inactivity (0 = unlimited)",
    order: 1,
  },
  {
    key: "max_failed_logins",
    value: "5",
    type: "number",
    group: "security",
    label: "Max Failed Login Attempts",
    description: "Lock account after N failures",
    order: 2,
  },
  {
    key: "lockout_duration_minutes",
    value: "15",
    type: "number",
    group: "security",
    label: "Lockout Duration (minutes)",
    description: "How long account stays locked",
    order: 3,
  },
  {
    key: "password_min_length",
    value: "8",
    type: "number",
    group: "security",
    label: "Min Password Length",
    description: "Minimum characters required",
    order: 4,
  },
  {
    key: "password_require_uppercase",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Require Uppercase",
    description: "At least one uppercase letter",
    order: 5,
  },
  {
    key: "password_require_number",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Require Number",
    description: "At least one digit",
    order: 6,
  },
  {
    key: "password_require_special",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Require Special Character",
    description: "At least one special char",
    order: 7,
  },
  {
    key: "password_expiry_days",
    value: "90",
    type: "number",
    group: "security",
    label: "Password Expiry (days)",
    description: "Force change after N days (0=never)",
    order: 8,
  },
  {
    key: "allowed_ip_ranges",
    value: "",
    type: "textarea",
    group: "security",
    label: "Allowed IP Ranges",
    description: "Restrict access by IP (one per line, blank=all)",
    order: 9,
  },
  {
    key: "enable_audit_log",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Enable Audit Logging",
    description: "Track all user actions",
    order: 10,
  },

  // ── Email & SMTP ──────────────────────────────────
  {
    key: "email_enabled",
    value: "false",
    type: "boolean",
    group: "email_smtp",
    label: "Email Enabled",
    description: "Send email notifications",
    order: 1,
  },
  {
    key: "email_from",
    value: "",
    type: "text",
    group: "email_smtp",
    label: "From Email",
    description: "Sender email address",
    order: 2,
  },
  {
    key: "smtp_host",
    value: "smtp.gmail.com",
    type: "text",
    group: "email_smtp",
    label: "SMTP Host",
    description: "Mail server host",
    order: 3,
  },
  {
    key: "smtp_port",
    value: "465",
    type: "number",
    group: "email_smtp",
    label: "SMTP Port",
    description: "Mail server port",
    order: 4,
  },
  {
    key: "smtp_user",
    value: "",
    type: "text",
    group: "email_smtp",
    label: "SMTP Username",
    description: "Mail server login",
    order: 5,
  },
  {
    key: "smtp_password",
    value: "ijdf sqcw gpbz qyqq",
    type: "secret",
    group: "email_smtp",
    label: "SMTP Password",
    description: "Mail server password",
    isSecret: true,
    order: 6,
  },
  {
    key: "notify_on_export_import",
    value: "true",
    type: "boolean",
    group: "email_smtp",
    label: "Notify on Export/Import",
    description: "Send admin email when data is exported or imported",
    order: 7,
  },

  // ── Backup ────────────────────────────────────────
  {
    key: "backup_enabled",
    value: "false",
    type: "boolean",
    group: "backup",
    label: "Auto Backup",
    description: "Enable scheduled backups",
    order: 1,
  },
  {
    key: "backup_frequency",
    value: "daily",
    type: "select",
    group: "backup",
    label: "Backup Frequency",
    description: "How often to backup",
    options: ["hourly", "daily", "weekly", "monthly"],
    order: 2,
  },
  {
    key: "backup_time",
    value: "02:00",
    type: "text",
    group: "backup",
    label: "Backup Time",
    description: "Scheduled time (24h)",
    order: 3,
  },
  {
    key: "backup_retention_days",
    value: "30",
    type: "number",
    group: "backup",
    label: "Retention (days)",
    description: "Keep backups for N days",
    order: 4,
  },
  {
    key: "backup_storage",
    value: "local",
    type: "select",
    group: "backup",
    label: "Storage Location",
    description: "Where to store backups",
    options: ["local", "s3", "gcs", "azure"],
    order: 5,
  },

  // ── Meetings ──────────────────────────────────────
  {
    key: "meeting_reminder_hours",
    value: "4",
    type: "number",
    group: "meetings",
    label: "Meeting Reminder (hours)",
    description: "Hours before meeting to send email notification",
    order: 1,
  },
  {
    key: "meeting_reminder_enabled",
    value: "true",
    type: "boolean",
    group: "meetings",
    label: "Enable Meeting Reminders",
    description: "Automatically send reminder emails for scheduled meetings",
    order: 2,
  },
];
