export const DEFAULT_SETTING_DEFS = [
    // ── General ───────────────────────────────────────
    {
        key: "org_name",
        value: "Constituency Management Portal",
        type: "text",
        group: "general",
        label: "Organization Name",
        description: "Display name of the portal",
        order: 1,
    },
    {
        key: "org_short_name",
        value: "CMP",
        type: "text",
        group: "general",
        label: "Short Name / Acronym",
        description: "Used in compact UI areas",
        order: 2,
    },
    {
        key: "constituency_name",
        value: "Chandni Chowk",
        type: "text",
        group: "general",
        label: "Constituency Name",
        description: "Name of the constituency",
        order: 3,
    },
    {
        key: "constituency_type",
        value: "Parliamentary",
        type: "select",
        group: "general",
        label: "Constituency Type",
        description: "Parliamentary or Assembly",
        options: ["Parliamentary", "Assembly", "Municipal"],
        order: 4,
    },
    {
        key: "state",
        value: "Delhi",
        type: "text",
        group: "general",
        label: "State",
        description: "State name",
        order: 5,
    },
    {
        key: "district",
        value: "Central Delhi",
        type: "text",
        group: "general",
        label: "District",
        description: "District name",
        order: 6,
    },
    {
        key: "representative_name",
        value: "Shri Example Singh",
        type: "text",
        group: "general",
        label: "Representative Name",
        description: "MP/MLA name",
        order: 7,
    },
    {
        key: "representative_title",
        value: "Member of Parliament",
        type: "select",
        group: "general",
        label: "Representative Title",
        description: "Designation",
        options: [
            "Member of Parliament",
            "Member of Legislative Assembly",
            "Municipal Councillor",
            "Mayor",
            "Sarpanch",
        ],
        order: 8,
    },
    {
        key: "org_address",
        value: "Constituency Office, Main Road",
        type: "textarea",
        group: "general",
        label: "Office Address",
        description: "Physical address",
        order: 9,
    },
    {
        key: "org_phone",
        value: "+91 11 1234 5678",
        type: "text",
        group: "general",
        label: "Office Phone",
        description: "Primary contact",
        order: 10,
    },
    {
        key: "org_email",
        value: "",
        type: "text",
        group: "general",
        label: "Office Email",
        description: "Primary email — used as recipient for export/import notifications",
        order: 11,
    },
    {
        key: "org_website",
        value: "",
        type: "text",
        group: "general",
        label: "Website URL",
        description: "Official website",
        order: 12,
    },
    {
        key: "timezone",
        value: "Asia/Kolkata",
        type: "select",
        group: "general",
        label: "Timezone",
        description: "System timezone",
        options: ["Asia/Kolkata", "Asia/Colombo", "Asia/Dhaka", "Asia/Kathmandu"],
        order: 13,
    },
    {
        key: "default_language",
        value: "en",
        type: "select",
        group: "general",
        label: "Default Language",
        description: "UI language",
        options: ["en", "hi", "mr", "ta", "te", "bn", "gu", "kn", "ml", "pa", "ur"],
        order: 14,
    },
    {
        key: "financial_year_start",
        value: "April",
        type: "select",
        group: "general",
        label: "Financial Year Start",
        description: "FY start month",
        options: ["January", "April"],
        order: 15,
    },
    {
        key: "date_format",
        value: "dd/MM/yyyy",
        type: "select",
        group: "general",
        label: "Date Format",
        description: "Display format",
        options: ["dd/MM/yyyy", "MM/dd/yyyy", "yyyy-MM-dd", "dd-MMM-yyyy"],
        order: 16,
    },
    {
        key: "currency_symbol",
        value: "₹",
        type: "text",
        group: "general",
        label: "Currency Symbol",
        description: "Currency display",
        order: 17,
    },

    // ── Grievance ─────────────────────────────────────
    {
        key: "grievance_sla_days",
        value: "7",
        type: "number",
        group: "grievance",
        label: "Default SLA (days)",
        description: "Expected resolution time",
        order: 1,
    },
    {
        key: "grievance_auto_assign",
        value: "false",
        type: "boolean",
        group: "grievance",
        label: "Auto-Assign by Category",
        description: "Auto-assign to department",
        order: 2,
    },
    {
        key: "grievance_escalation_days",
        value: "3",
        type: "number",
        group: "grievance",
        label: "Auto Escalation (days)",
        description: "Escalate if not acted upon",
        order: 3,
    },
    {
        key: "grievance_allow_anonymous",
        value: "false",
        type: "boolean",
        group: "grievance",
        label: "Allow Anonymous Complaints",
        description: "Accept without citizen name",
        order: 4,
    },
    {
        key: "grievance_require_phone",
        value: "true",
        type: "boolean",
        group: "grievance",
        label: "Require Phone Number",
        description: "Mandatory phone for tracking",
        order: 5,
    },
    {
        key: "grievance_ticket_prefix",
        value: "GRV",
        type: "text",
        group: "grievance",
        label: "Ticket Number Prefix",
        description: "e.g. GRV-2025-00001",
        order: 6,
    },
    {
        key: "grievance_categories",
        value:
            "Water Supply,Road Damage,Electricity,Sanitation,Drainage,Street Light,Health,Education,Law & Order,Encroachment,Noise,Other",
        type: "textarea",
        group: "grievance",
        label: "Grievance Categories",
        description: "Comma-separated list",
        order: 7,
    },
    {
        key: "grievance_sources",
        value: "WALK_IN,PHONE,EMAIL,WHATSAPP,SOCIAL_MEDIA,CAMP,REFERRAL,ONLINE",
        type: "textarea",
        group: "grievance",
        label: "Grievance Sources",
        description: "Comma-separated intake channels",
        order: 8,
    },

    // ── Notifications ─────────────────────────────────
    {
        key: "sms_enabled",
        value: "false",
        type: "boolean",
        group: "notifications",
        label: "SMS Enabled",
        description: "Send SMS notifications",
        order: 1,
    },
    {
        key: "sms_provider",
        value: "twilio",
        type: "select",
        group: "notifications",
        label: "SMS Provider",
        description: "Gateway provider",
        options: ["twilio", "msg91", "textlocal", "fast2sms", "custom"],
        order: 2,
    },
    {
        key: "sms_api_key",
        value: "",
        type: "secret",
        group: "notifications",
        label: "SMS API Key",
        description: "Provider API key",
        isSecret: true,
        order: 3,
    },
    {
        key: "sms_sender_id",
        value: "CONSTY",
        type: "text",
        group: "notifications",
        label: "SMS Sender ID",
        description: "6-char sender ID",
        order: 4,
    },
    {
        key: "whatsapp_enabled",
        value: "false",
        type: "boolean",
        group: "notifications",
        label: "WhatsApp Enabled",
        description: "Send WhatsApp messages",
        order: 5,
    },
    {
        key: "whatsapp_waba_id",
        value: "",
        type: "text",
        group: "notifications",
        label: "WhatsApp WABA ID",
        description: "WhatsApp Business Account ID (WABA ID)",
        order: 6,
    },
    {
        key: "whatsapp_phone_number_id",
        value: "",
        type: "text",
        group: "notifications",
        label: "Phone Number ID",
        description: "Phone Number ID from Meta Cloud API Console",
        order: 7,
    },
    {
        key: "whatsapp_business_phone",
        value: "",
        type: "text",
        group: "notifications",
        label: "Sender Phone Number",
        description: "Official WhatsApp Sender Phone Number (e.g. +919876543210)",
        order: 8,
    },
    {
        key: "whatsapp_api_key",
        value: "",
        type: "secret",
        group: "notifications",
        label: "WhatsApp Access Token / API Key",
        description: "Meta WhatsApp System User / Permanent Access Token",
        isSecret: true,
        order: 9,
    },
    {
        key: "notify_on_grievance_create",
        value: "true",
        type: "boolean",
        group: "notifications",
        label: "Notify on Grievance Filed",
        description: "Send confirmation to citizen",
        order: 7,
    },
    {
        key: "notify_on_grievance_resolve",
        value: "true",
        type: "boolean",
        group: "notifications",
        label: "Notify on Grievance Resolved",
        description: "Send resolution notice",
        order: 8,
    },
    {
        key: "notify_birthday_reminder",
        value: "true",
        type: "boolean",
        group: "notifications",
        label: "Birthday Reminders",
        description: "Daily leader birthday alerts",
        order: 9,
    },
];
